### ISSUE TITLE
Consider moving tarballs to releases

### ISSUE THREAD

**Issue by mrakitin** [bluesky/libhkl#3]
It would be more natural to attach the `.tar.gz` files to releases rather than committing to the repo.
We should check actions linked in https://github.com/actions/create-release.

**Comment by prjemian** [comment]
Should we start with the v5.0.0.2173 version?  That's the version in current use, although the conda-forge package was not built with the tarball in this repo.

**Comment by mrakitin** [comment]
Makes sense to start with that initial version.

**Comment by prjemian** [comment]
It's not necessary to use a workflow to add a release artifact.  Just drop it into the web page box when creating the release, as shown here:
![image](https://github.com/bluesky/libhkl/assets/2279984/515db0a3-f538-4326-b208-58010563a0ee)
