### ISSUE TITLE
pick a versioning scheme

### ISSUE THREAD

**Issue by prjemian** [bluesky/libhkl#5]
What versioning scheme should this repo use?  Seems we have a choice.  Upvote whichever comment below.

**Comment by prjemian** [comment]
## [semver](https://semver.org) starting from 1.0.0

  * Clear identification of a new libhkl release.
  * Need to examine release notes to find a specific version.

**Comment by prjemian** [comment]
## Same versioning as [hkl repo](https://repo.or.cz/hkl.git)
  * Easy to correlate release of libhkl with hkl repo version.
  * Verbose if/when changes are need to a released version of libhkl

**Comment by prjemian** [comment]
@mrakitin @klauer   Thoughts?  Votes?

**Comment by klauer** [comment]
It might be easier to just follow semver and decouple from the upstream (which is far from semver as far as I can tell).

That said, we are just packaging/building that library so it _sorta_ makes sense to follow their versioning. So I'm a bit split and both get a 👍 from my indecisive self.

**Comment by prjemian** [comment]
FWIW: the conda-forge recipe builds with the 2173 release

**Comment by prjemian** [comment]
Progress noted, I will plough ahead with semver (since, if we change our minds and track hkl versioning scheme, that is still in the sequence of semver, in that v1.0.0 < v5.0.0.3375).  If we switch to hkl's versioning, we cannot go back to semver.

**Comment by prjemian** [comment]
Which means I will delete the `https://github.com/bluesky/libhkl/releases/tag/v5.0.0.2173rc1` tag.

**Comment by prjemian** [comment]
semver it is.
